import React from 'react'
import 'bootstrap/dist/css/bootstrap.min.css';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "../styles/styles.scss";
import { Providers } from '@/store/Providers';
import { Container, Nav, NavLink, Navbar, NavbarBrand } from 'react-bootstrap';
import { NextUIProvider } from '@nextui-org/react';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Bocking - Alejo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <Providers>
          <Navbar bg="primary" data-bs-theme="dark">
            <Container>
              <NavbarBrand>Bocking</NavbarBrand>
              <Nav className="me-auto">
                <NavLink href="#home">Inicio</NavLink>
                <NavLink href="#features">Contacto</NavLink>
                <NavLink href="#pricing">Precios</NavLink>
              </Nav>
            </Container>
          </Navbar>
          {children}
        </Providers>
      </body>
    </html>
  )
}
